name: Build and push Apptainer images

on:
  push:
    branches: [main]
    paths:
      - 'apptainer/*.def'
      - '.github/workflows/build-and-push-apptainer.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag (e.g. 25.06). Defaults to latest + commit SHA.'
        required: false
        type: string

jobs:
  build-push:
    strategy:
      matrix:
        image: [slurm-ci, jureca, leonardo, lumi, jupiter]
    name: Build & Publish SIF Artifact (${{ matrix.image }})
    runs-on: "runs-on=${{ github.run_id }}/family=i7ie.large/spot=false"
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check disk space
        run: |
          echo "Disk info:"
          df -h

      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build SIF from definition file
        env:
          APPTAINER_CACHEDIR: /mnt/ephemeral/apptainer-cache
          APPTAINER_TMPDIR: /mnt/ephemeral/apptainer-tmp
        run: |
          sudo mkdir -p $APPTAINER_CACHEDIR $APPTAINER_TMPDIR
          sudo APPTAINER_CACHEDIR=$APPTAINER_CACHEDIR APPTAINER_TMPDIR=$APPTAINER_TMPDIR apptainer --verbose build --mksquashfs-args="-comp gzip -Xcompression-level 1" eval_env-${{ matrix.image }}.sif apptainer/${{ matrix.image }}.def

      - name: Install Hugging Face Hub CLI
        run: pip install --upgrade "huggingface_hub"

      - name: Login to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: hf auth login --token "$HF_TOKEN"

      - name: Upload SIF to Hugging Face Hub
        env:
          HF_REPO: openeurollm/evaluation_singularity_images
        run: |
          hf upload \
            "$HF_REPO" \
            eval_env-${{ matrix.image }}.sif \
            eval_env-${{ matrix.image }}.sif \
            --repo-type dataset \
            --commit-message "[chore] update ${{ matrix.image }} image"
